default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

# production:
# adapter: postgresql
# database: railway
# username: postgres
# password: yaCniONkuqSMh59m0fB0
# host: containers-us-west-169.railway.app
# port: 6138
# pool: 5
